name: Fetch the data
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 1 * *' # 1AM every 1st of the month
jobs:
  scrape:
    name: Fetch the data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip3 install -r requirements.txt
      - name: Fetch the data
        run: python3 run.py
      - name: Commit the data
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: |
            git config --global user.name 'Pierre Mesure (Github Actions)'
            git config --global user.email 'pierre@mesu.re'
            git config --global rebase.autoStash true
            git pull --rebase
            git add .
            git commit -am "Update the data"
            git push
